"""create social posts table

Revision ID: 7c6d33c8ad23
Revises: c6a9d58c6d8a
Create Date: 2026-08-15 16:06:21.659735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6d33c8ad23'
down_revision: Union[str, Sequence[str], None] = 'c6a9d58c6d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'platform', name='uq_campaign_platform'),
    sa.UniqueConstraint('idempotency_key', name='uq_social_post_idempotency_key')
    )
    op.create_index('ix_social_posts_status_scheduled_at', 'social_posts', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_posts_status_scheduled_at', table_name='social_posts')
    op.drop_table('social_posts')
    # ### end Alembic commands ###
