"""add social post error message

Revision ID: 88c75fcbfd0f
Revises: 28b81f352716
Create Date: 2026-08-17 11:56:26.353625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c75fcbfd0f'
down_revision: Union[str, Sequence[str], None] = '28b81f352716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_posts', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_posts', 'error_message')
    # ### end Alembic commands ###
